//DATA FECTHING
export const DATA_FETCHING='DATA_FETCHING';
export const DATA_FETCHING_SUCCESS='DATA_FETCHING_SUCCESS';
export const DATA_FETCHING_FAILURE='DATA_FETCHING_FAILURE';

//DATA SENDING
export const DATA_SENDING='DATA_SENDING';
export const DATA_SENDING_SUCCESS='DATA_SENDING_SUCCESS';
export const DATA_SENDING_FAILURE='DATA_SENDING_FAILURE';

//CONSENTS 
export const CONSENTS_SENDING='CONSENTS_SENDING';
export const CONSENTS_SENDING_SUCCESS='CONSENTS_SENDING_SUCCESS';
export const CONSENTS_SENDING_FAILURE='CONSENTS_SENDING_FAILURE';

//MEDICATION
export const MEDICATION_SENDING='MEDICATION_SENDING';
export const MEDICATION_SENDING_SUCCESS='MEDICATION_SENDING_SUCCESS';
export const MEDICATION_SENDING_FAILURE='MEDICATION_SENDING_FAILURE';


//USER ACTIVITE
export const USER_LOGOUT='USER_LOGOUT';